// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gym/ent/coach"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Coach is the model entity for the Coach schema.
type Coach struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Price holds the value of the "price" field.
	Price        int `json:"price,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Coach) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case coach.FieldID, coach.FieldPrice:
			values[i] = new(sql.NullInt64)
		case coach.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Coach fields.
func (_m *Coach) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case coach.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case coach.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case coach.FieldPrice:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Coach.
// This includes values selected through modifiers, order, etc.
func (_m *Coach) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Coach.
// Note that you need to call Coach.Unwrap() before calling this method if this Coach
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Coach) Update() *CoachUpdateOne {
	return NewCoachClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Coach entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Coach) Unwrap() *Coach {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Coach is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Coach) String() string {
	var builder strings.Builder
	builder.WriteString("Coach(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteByte(')')
	return builder.String()
}

// Coaches is a parsable slice of Coach.
type Coaches []*Coach
