// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gym/ent/predicate"
	"gym/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UserUpdate) SetPassword(v int) *UserUpdate {
	_u.mutation.ResetPassword()
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePassword(v *int) *UserUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// AddPassword adds value to the "password" field.
func (_u *UserUpdate) AddPassword(v int) *UserUpdate {
	_u.mutation.AddPassword(v)
	return _u
}

// SetCoachID sets the "coach_id" field.
func (_u *UserUpdate) SetCoachID(v int) *UserUpdate {
	_u.mutation.ResetCoachID()
	_u.mutation.SetCoachID(v)
	return _u
}

// SetNillableCoachID sets the "coach_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCoachID(v *int) *UserUpdate {
	if v != nil {
		_u.SetCoachID(*v)
	}
	return _u
}

// AddCoachID adds value to the "coach_id" field.
func (_u *UserUpdate) AddCoachID(v int) *UserUpdate {
	_u.mutation.AddCoachID(v)
	return _u
}

// ClearCoachID clears the value of the "coach_id" field.
func (_u *UserUpdate) ClearCoachID() *UserUpdate {
	_u.mutation.ClearCoachID()
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *UserUpdate) SetCourseID(v int) *UserUpdate {
	_u.mutation.ResetCourseID()
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCourseID(v *int) *UserUpdate {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// AddCourseID adds value to the "course_id" field.
func (_u *UserUpdate) AddCourseID(v int) *UserUpdate {
	_u.mutation.AddCourseID(v)
	return _u
}

// ClearCourseID clears the value of the "course_id" field.
func (_u *UserUpdate) ClearCourseID() *UserUpdate {
	_u.mutation.ClearCourseID()
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *UserUpdate) SetLastName(v string) *UserUpdate {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastName(v *string) *UserUpdate {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserUpdate) SetCreatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCreatedAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPassword(); ok {
		_spec.AddField(user.FieldPassword, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CoachID(); ok {
		_spec.SetField(user.FieldCoachID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCoachID(); ok {
		_spec.AddField(user.FieldCoachID, field.TypeInt, value)
	}
	if _u.mutation.CoachIDCleared() {
		_spec.ClearField(user.FieldCoachID, field.TypeInt)
	}
	if value, ok := _u.mutation.CourseID(); ok {
		_spec.SetField(user.FieldCourseID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCourseID(); ok {
		_spec.AddField(user.FieldCourseID, field.TypeInt, value)
	}
	if _u.mutation.CourseIDCleared() {
		_spec.ClearField(user.FieldCourseID, field.TypeInt)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(user.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UserUpdateOne) SetPassword(v int) *UserUpdateOne {
	_u.mutation.ResetPassword()
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePassword(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// AddPassword adds value to the "password" field.
func (_u *UserUpdateOne) AddPassword(v int) *UserUpdateOne {
	_u.mutation.AddPassword(v)
	return _u
}

// SetCoachID sets the "coach_id" field.
func (_u *UserUpdateOne) SetCoachID(v int) *UserUpdateOne {
	_u.mutation.ResetCoachID()
	_u.mutation.SetCoachID(v)
	return _u
}

// SetNillableCoachID sets the "coach_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCoachID(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetCoachID(*v)
	}
	return _u
}

// AddCoachID adds value to the "coach_id" field.
func (_u *UserUpdateOne) AddCoachID(v int) *UserUpdateOne {
	_u.mutation.AddCoachID(v)
	return _u
}

// ClearCoachID clears the value of the "coach_id" field.
func (_u *UserUpdateOne) ClearCoachID() *UserUpdateOne {
	_u.mutation.ClearCoachID()
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *UserUpdateOne) SetCourseID(v int) *UserUpdateOne {
	_u.mutation.ResetCourseID()
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCourseID(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// AddCourseID adds value to the "course_id" field.
func (_u *UserUpdateOne) AddCourseID(v int) *UserUpdateOne {
	_u.mutation.AddCourseID(v)
	return _u
}

// ClearCourseID clears the value of the "course_id" field.
func (_u *UserUpdateOne) ClearCourseID() *UserUpdateOne {
	_u.mutation.ClearCourseID()
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *UserUpdateOne) SetLastName(v string) *UserUpdateOne {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserUpdateOne) SetCreatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCreatedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPassword(); ok {
		_spec.AddField(user.FieldPassword, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CoachID(); ok {
		_spec.SetField(user.FieldCoachID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCoachID(); ok {
		_spec.AddField(user.FieldCoachID, field.TypeInt, value)
	}
	if _u.mutation.CoachIDCleared() {
		_spec.ClearField(user.FieldCoachID, field.TypeInt)
	}
	if value, ok := _u.mutation.CourseID(); ok {
		_spec.SetField(user.FieldCourseID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCourseID(); ok {
		_spec.AddField(user.FieldCourseID, field.TypeInt, value)
	}
	if _u.mutation.CourseIDCleared() {
		_spec.ClearField(user.FieldCourseID, field.TypeInt)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(user.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
