// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gym/ent/predicate"
	"gym/ent/wallet"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WalletUpdate is the builder for updating Wallet entities.
type WalletUpdate struct {
	config
	hooks    []Hook
	mutation *WalletMutation
}

// Where appends a list predicates to the WalletUpdate builder.
func (_u *WalletUpdate) Where(ps ...predicate.Wallet) *WalletUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *WalletUpdate) SetAmount(v int) *WalletUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *WalletUpdate) SetNillableAmount(v *int) *WalletUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *WalletUpdate) AddAmount(v int) *WalletUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetUserid sets the "userid" field.
func (_u *WalletUpdate) SetUserid(v int) *WalletUpdate {
	_u.mutation.ResetUserid()
	_u.mutation.SetUserid(v)
	return _u
}

// SetNillableUserid sets the "userid" field if the given value is not nil.
func (_u *WalletUpdate) SetNillableUserid(v *int) *WalletUpdate {
	if v != nil {
		_u.SetUserid(*v)
	}
	return _u
}

// AddUserid adds value to the "userid" field.
func (_u *WalletUpdate) AddUserid(v int) *WalletUpdate {
	_u.mutation.AddUserid(v)
	return _u
}

// Mutation returns the WalletMutation object of the builder.
func (_u *WalletUpdate) Mutation() *WalletMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WalletUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WalletUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WalletUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WalletUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WalletUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(wallet.Table, wallet.Columns, sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(wallet.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(wallet.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Userid(); ok {
		_spec.SetField(wallet.FieldUserid, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserid(); ok {
		_spec.AddField(wallet.FieldUserid, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WalletUpdateOne is the builder for updating a single Wallet entity.
type WalletUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WalletMutation
}

// SetAmount sets the "amount" field.
func (_u *WalletUpdateOne) SetAmount(v int) *WalletUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *WalletUpdateOne) SetNillableAmount(v *int) *WalletUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *WalletUpdateOne) AddAmount(v int) *WalletUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetUserid sets the "userid" field.
func (_u *WalletUpdateOne) SetUserid(v int) *WalletUpdateOne {
	_u.mutation.ResetUserid()
	_u.mutation.SetUserid(v)
	return _u
}

// SetNillableUserid sets the "userid" field if the given value is not nil.
func (_u *WalletUpdateOne) SetNillableUserid(v *int) *WalletUpdateOne {
	if v != nil {
		_u.SetUserid(*v)
	}
	return _u
}

// AddUserid adds value to the "userid" field.
func (_u *WalletUpdateOne) AddUserid(v int) *WalletUpdateOne {
	_u.mutation.AddUserid(v)
	return _u
}

// Mutation returns the WalletMutation object of the builder.
func (_u *WalletUpdateOne) Mutation() *WalletMutation {
	return _u.mutation
}

// Where appends a list predicates to the WalletUpdate builder.
func (_u *WalletUpdateOne) Where(ps ...predicate.Wallet) *WalletUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WalletUpdateOne) Select(field string, fields ...string) *WalletUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Wallet entity.
func (_u *WalletUpdateOne) Save(ctx context.Context) (*Wallet, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WalletUpdateOne) SaveX(ctx context.Context) *Wallet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WalletUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WalletUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WalletUpdateOne) sqlSave(ctx context.Context) (_node *Wallet, err error) {
	_spec := sqlgraph.NewUpdateSpec(wallet.Table, wallet.Columns, sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Wallet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wallet.FieldID)
		for _, f := range fields {
			if !wallet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wallet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(wallet.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(wallet.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Userid(); ok {
		_spec.SetField(wallet.FieldUserid, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserid(); ok {
		_spec.AddField(wallet.FieldUserid, field.TypeInt, value)
	}
	_node = &Wallet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
