// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Coach is the predicate function for coach builders.
type Coach func(*sql.Selector)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Wallet is the predicate function for wallet builders.
type Wallet func(*sql.Selector)
